version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db
        ports:
            - "9000:9000"

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        ports:
            - "3306:3306"

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel
        ports:
            - "8080:80"

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
